# ALS factorization

In [ ]:
## GD 

In [ ]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

In [ ]:
def matrix_factorization(R, P, Q, K, steps=5000, alpha=0.0002, beta=0.02):
    '''
    R: rating matrix
    P: |U| * K (User features matrix)
    Q: K * |I| (Item features matrix)
    K: latent features
    steps: iterations
    alpha: learning rate
    beta: regularization parameter'''   
    
    for step in range(steps):        
        for i in range(len(R)):
            for j in range(len(R[i])):
                if R[i][j] > 0:
                    # calculate error between Rij and R_hat_ij
                    eij = R[i][j] - np.dot(P[i,:],Q[:,j])

                    for k in range(K):
                        # calculate gradient with alpha and beta parameter
                        P[i][k] = P[i][k] + alpha * (2 * eij * Q[k][j] - beta * P[i][k])
                        Q[k][j] = Q[k][j] + alpha * (2 * eij * P[i][k] - beta * Q[k][j])

        eR = np.dot(P,Q) # R hat
        # in kết quả sau 1000 lần lặp
        if step%1000 == 0:
           print("-------- Result at step", step, ": with eR, P, Q are :-----")
           display(eR, P, Q)

        e = 0 # error

        for i in range(len(R)):
            for j in range(len(R[i])):
                if R[i][j] > 0:
                    e = e + pow(R[i][j] - np.dot(P[i,:],Q[:,j]), 2)
                    for k in range(K):
                        e = e + (beta/2) * (pow(P[i][k],2) + pow(Q[k][j],2))
        # 0.001: local minimum
        if e < 0.001:
            break
    return P, Q

In [ ]:
# 1, Fill P, Q with random number
# 2. P x Q => R new
# 3. Find error with this formular (error: difference bw Rnew and R)
#4. Decrease error by using gradient descent (derivative the error, it help us know if we need to go up or down value of matrix) 
#=> update matrix P, Q (repeat to reduce error) => multiply P x Q together 

## Example 1:

In [ ]:
R = [
     [0, 4.5, 2.0, 0],
     [4, 0, 3.5, 0],
     [0, 5, 0, 2], 
     [0, 3.5, 4.0, 1.0]
    ]

R = np.array(R)
# N: num of User
N = len(R)
# M: num of Movie
M = len(R[0])
# Num of Features
K = 2
 
P = np.random.rand(N,K)
Q = np.random.rand(K,M)

nP, nQ = matrix_factorization(R, P, Q, K, steps=10000)

Result at step 0 : with eR, P, Q are :


array([[0.87546796, 0.63104916, 0.58033183, 0.45188674],
       [0.39494539, 0.38628617, 0.37933898, 0.14069071],
       [0.63255725, 0.56067919, 0.54045587, 0.26139868],
       [0.58268902, 0.57230603, 0.56243156, 0.20608287]])

array([[0.39310061, 0.69497862],
       [0.59397096, 0.01182352],
       [0.71345326, 0.19118658],
       [0.88613529, 0.01033975]])

array([[0.64713453, 0.63947046, 0.6291103 , 0.22647141],
       [0.89366632, 0.5463088 , 0.47919199, 0.52211778]])

Result at step 1000 : with eR, P, Q are :


array([[3.03509199, 3.96158227, 2.71474988, 1.4780537 ],
       [3.59192622, 4.79384517, 3.60788126, 1.64897123],
       [3.67084825, 4.89257734, 3.66243251, 1.69147591],
       [2.95593806, 4.01297388, 3.22356566, 1.29242136]])

array([[1.06385372, 1.23951452],
       [1.69918235, 0.95604711],
       [1.7089747 , 1.00902135],
       [1.68186143, 0.4576705 ]])

array([[1.42374518, 1.97837376, 1.72311949, 0.57924339],
       [1.22663782, 1.498072  , 0.71124847, 0.69529115]])

Result at step 2000 : with eR, P, Q are :


array([[3.30718485, 4.12957048, 2.45824665, 1.59728587],
       [3.91766031, 4.83411215, 3.60220876, 1.71762724],
       [4.07761563, 5.03341451, 3.72622607, 1.79358663],
       [3.11793266, 3.79973975, 3.43546561, 1.22324344]])

array([[0.9903813 , 1.37964188],
       [1.69889209, 1.00769984],
       [1.75069393, 1.06977768],
       [1.78516566, 0.28578336]])

array([[1.53977781, 1.86348079, 1.85204364, 0.56478998],
       [1.29179733, 1.6555122 , 0.4523038 , 0.75231729]])

Result at step 3000 : with eR, P, Q are :


array([[3.43849957, 4.30967913, 2.21911561, 1.72984062],
       [3.9609007 , 4.76218804, 3.53746158, 1.74059391],
       [4.18404145, 5.03495268, 3.71499993, 1.8442384 ],
       [3.15966829, 3.61139285, 3.73141163, 1.15485319]])

array([[0.93015008, 1.50887357],
       [1.67013288, 1.01955395],
       [1.75095224, 1.09291769],
       [1.88722541, 0.14724433]])

array([[1.57205075, 1.77618041, 1.95655089, 0.54888379],
       [1.30975615, 1.76129056, 0.26458786, 0.80808382]])

Result at step 4000 : with eR, P, Q are :


array([[3.50591885, 4.41473037, 2.08323706, 1.83418369],
       [3.97958894, 4.73603758, 3.50459893, 1.76976181],
       [4.21905907, 5.02809282, 3.68621265, 1.88427494],
       [3.17402645, 3.5121888 , 3.893722  , 1.11062063]])

array([[0.90232695, 1.57729978],
       [1.66019563, 1.02467897],
       [1.74376505, 1.10600327],
       [1.93701257, 0.07932527]])

array([[1.58471943, 1.73932478, 2.00300608, 0.53835826],
       [1.31616312, 1.80389979, 0.17490061, 0.85488411]])

Result at step 5000 : with eR, P, Q are :


array([[3.53722539, 4.45516729, 2.03280105, 1.90337575],
       [3.9870705 , 4.7259182 , 3.49245401, 1.79116812],
       [4.22590629, 5.01981477, 3.65780346, 1.91139929],
       [3.17917032, 3.48074639, 3.95231583, 1.08386362]])

array([[0.89476289, 1.60567654],
       [1.65923996, 1.02507879],
       [1.73487389, 1.11513941],
       [1.95551505, 0.05451816]])

array([[1.58901574, 1.72947803, 2.01715501, 0.52943698],
       [1.31747149, 1.81088435, 0.14194988, 0.89037558]])

Result at step 6000 : with eR, P, Q are :


array([[3.55307937, 4.46868043, 2.01685815, 1.95014821],
       [3.98950214, 4.72038981, 3.48881537, 1.80480659],
       [4.2242117 , 5.012805  , 3.63348593, 1.93003281],
       [3.18091823, 3.47521244, 3.97002536, 1.06542505]])

array([[0.89423872, 1.61818724],
       [1.66116713, 1.02345596],
       [1.72637952, 1.12293484],
       [1.96229954, 0.0458083 ]])

array([[1.5902736 , 1.72882656, 2.02011434, 0.52154221],
       [1.31690269, 1.80615488, 0.13001813, 0.91693034]])

Result at step 7000 : with eR, P, Q are :


array([[3.56287616, 4.47341224, 2.01178755, 1.98356499],
       [3.99011224, 4.71620134, 3.48806675, 1.81332391],
       [4.22083861, 5.00722833, 3.61272894, 1.94363292],
       [3.18177226, 3.47703013, 3.97484817, 1.05162775]])

array([[0.89561489, 1.62511307],
       [1.66376824, 1.021197  ],
       [1.71876116, 1.13007043],
       [1.96519991, 0.04245027]])

array([[1.59063581, 1.73044045, 2.01992325, 0.51488904],
       [1.31577247, 1.79901574, 0.12473853, 0.93681032]])

Result at step 8000 : with eR, P, Q are :


array([[3.57009108, 4.4754188 , 2.00993556, 2.00816303],
       [3.99013364, 4.71231048, 3.48822423, 1.81844127],
       [4.21785187, 5.00280744, 3.594854  , 1.95393274],
       [3.18269298, 3.48032639, 3.9758691 , 1.04103359]])

array([[0.89738906, 1.62985324],
       [1.66634569, 1.01880644],
       [1.71206084, 1.13671383],
       [1.96672302, 0.04105027]])

array([[1.59083464, 1.73220001, 2.0190338 , 0.50946163],
       [1.31453153, 1.79216225, 0.1215304 , 0.95160576]])

Result at step 9000 : with eR, P, Q are :


array([[3.57599118, 4.47652168, 2.00906266, 2.02637294],
       [3.98998269, 4.70835329, 3.48863198, 1.82114519],
       [4.2157835 , 4.99931162, 3.57937764, 1.9618352 ],
       [3.18398128, 3.48347292, 3.97581013, 1.03286826]])

array([[0.89917214, 1.63350921],
       [1.66869976, 1.01644541],
       [1.7062052 , 1.14293856],
       [1.96765171, 0.04054981]])

array([[1.59109785, 1.73356056, 2.01813362, 0.50508945],
       [1.31332   , 1.78618663, 0.11901564, 0.96247427]])

In [ ]:
nR = np.dot(nP, nQ)
nR

array([[3.58108725, 4.47726162, 2.00852826, 2.03973315],
       [3.98979673, 4.704216  , 3.48907243, 1.82206513],
       [4.21468303, 4.99656865, 3.56591578, 1.9679006 ],
       [3.18568922, 3.48609633, 3.97548   , 1.02659755]])

In [ ]:
nP

array([[0.90087817, 1.63648273],
       [1.67079152, 1.01416077],
       [1.70108839, 1.14879918],
       [1.96825481, 0.04057504]])

In [ ]:
nQ

array([[1.59148481, 1.73444421, 2.01739213, 0.50157515],
       [1.31217598, 1.78109958, 0.11677711, 0.97029747]])

### Example 2

In [ ]:
R = [
     [2, 5, 1, 3],
     [4, 0, 0, 1],
     [0, 4, 2, 0], 
     [2, 4, 3, 1],
     [1, 3, 2, 0]
    ]

R = np.array(R)
# N: num of User
N = len(R)
# M: num of Movie
M = len(R[0])
# Num of Features
K = 2

 
P = np.random.rand(N,K)
Q = np.random.rand(K,M)


nP, nQ = matrix_factorization(R, P, Q, K, steps=10000)

nR = np.dot(nP, nQ)

nR

Result at step 0 : with eR, P, Q are :


array([[0.48103175, 0.75899282, 0.89712912, 1.54704663],
       [0.35824397, 0.61011264, 0.66456307, 1.18425959],
       [0.27630745, 0.12534194, 0.54000593, 0.66628343],
       [0.34057971, 0.32064826, 0.6524113 , 0.94019989],
       [0.42595015, 0.610513  , 0.79929513, 1.32582674]])

array([[0.99198854, 0.88831737],
       [0.81363637, 0.61108737],
       [0.05142716, 0.85979177],
       [0.3406619 , 0.87282688],
       [0.77565106, 0.85588049]])

array([[0.20829321, 0.67048932, 0.36129879, 0.91457951],
       [0.30890679, 0.10567742, 0.6064554 , 0.72023161]])

Result at step 1000 : with eR, P, Q are :


array([[2.59276608, 4.72620736, 1.95876183, 2.05718924],
       [2.38045839, 4.30637492, 1.96195494, 1.79226017],
       [2.18200554, 3.88981784, 2.0851408 , 1.47372963],
       [2.26638306, 4.04094942, 2.16221749, 1.53281499],
       [1.69621713, 3.05575667, 1.46173984, 1.23950486]])

array([[1.61361031, 1.07078497],
       [1.2592654 , 1.19749855],
       [0.76476299, 1.47347796],
       [0.79916541, 1.52579763],
       [0.81072845, 0.93681408]])

array([[0.95201354, 1.79557547, 0.41922468, 0.93228619],
       [0.98674079, 1.70795101, 1.19752947, 0.51629659]])

Result at step 2000 : with eR, P, Q are :


array([[2.52708038, 4.8309261 , 1.47528102, 2.0906763 ],
       [2.98228836, 5.48407649, 2.57840677, 1.84143381],
       [2.19653471, 3.96131203, 2.19942957, 1.1317791 ],
       [2.2886991 , 4.07126276, 2.5087705 , 1.01704511],
       [1.60921064, 2.9239103 , 1.52722743, 0.892014  ]])

array([[1.82408041, 0.74893512],
       [1.40886555, 1.57497989],
       [0.77087299, 1.40792237],
       [0.61042227, 1.64614525],
       [0.63945591, 0.96204689]])

array([[0.96084108, 1.92623362, 0.21591555, 1.05276747],
       [1.03404017, 1.75892551, 1.44396179, 0.22744798]])

Result at step 3000 : with eR, P, Q are :


array([[2.34916766, 4.95306614, 1.07390756, 2.45514033],
       [3.26807286, 6.1249733 , 3.23658956, 1.66560328],
       [2.12235308, 3.92771865, 2.21563983, 0.96746862],
       [2.28733561, 4.0682147 , 2.76307191, 0.66590917],
       [1.5643716 , 2.86246511, 1.70740563, 0.63853084]])

array([[2.02290524, 0.50748313],
       [1.37164943, 1.89326727],
       [0.79662875, 1.3070147 ],
       [0.54796497, 1.66424634],
       [0.52570597, 1.01399513]])

array([[8.90005841e-01, 2.00048973e+00, 1.24665905e-01, 1.21352910e+00],
       [1.08135649e+00, 1.78580318e+00, 1.61920702e+00, 5.63453762e-04]])

Result at step 4000 : with eR, P, Q are :


array([[2.17555035, 4.99504881, 0.97038182, 2.73735316],
       [3.47941946, 6.55532953, 3.89274336, 1.44231109],
       [2.04868061, 3.91559288, 2.20089302, 0.96354797],
       [2.2591385 , 4.08634963, 2.80501289, 0.58844397],
       [1.53437382, 2.82362073, 1.82635938, 0.49844218]])

array([[2.11540824, 0.39016523],
       [1.2942259 , 2.16440391],
       [0.84338766, 1.21441524],
       [0.59266307, 1.58793777],
       [0.47282043, 1.0266716 ]])

array([[ 0.82266095,  2.02611173,  0.14274351,  1.31626841],
       [ 1.11564683,  1.81716696,  1.71317424, -0.12069723]])

Result at step 5000 : with eR, P, Q are :


array([[2.06275864, 4.99853999, 0.98249336, 2.88304493],
       [3.62655382, 6.87546991, 4.42814452, 1.28331732],
       [1.9764139 , 3.91414217, 2.1772623 , 1.03016674],
       [2.20409815, 4.10614698, 2.79370929, 0.63639267],
       [1.50225878, 2.81014595, 1.8878862 , 0.45650676]])

array([[2.14509012, 0.34280068],
       [1.23378368, 2.36582523],
       [0.89412876, 1.13526781],
       [0.65361455, 1.50473849],
       [0.46074273, 1.01499274]])

array([[ 0.7818073 ,  2.0354309 ,  0.17335392,  1.37164756],
       [ 1.12517725,  1.84467916,  1.78130795, -0.17287797]])

Result at step 6000 : with eR, P, Q are :


array([[2.00382295, 4.99413766, 1.00504958, 2.94760608],
       [3.71906218, 7.11405087, 4.84614869, 1.19210273],
       [1.91713171, 3.91960404, 2.14901427, 1.11563407],
       [2.14919224, 4.1160624 , 2.79366502, 0.6987374 ],
       [1.47050615, 2.80970466, 1.92053749, 0.46506015]])

array([[2.1492648 , 0.32499463],
       [1.19446745, 2.50877182],
       [0.94303523, 1.07005514],
       [0.69669137, 1.44540113],
       [0.46817819, 0.99476401]])

array([[ 0.76310893,  2.04186493,  0.18914906,  1.40041905],
       [ 1.11909476,  1.86350534,  1.84162476, -0.19158866]])

Result at step 7000 : with eR, P, Q are :


array([[1.97576879, 4.99012449, 1.01902928, 2.97455572],
       [3.77636003, 7.28828923, 5.17851972, 1.14221497],
       [1.87376776, 3.92900102, 2.12043024, 1.19822457],
       [2.10474282, 4.11681993, 2.80765079, 0.74711126],
       [1.44334468, 2.8142225 , 1.93818153, 0.49432154]])

array([[2.14491982, 0.3186882 ],
       [1.1680931 , 2.61249209],
       [0.98706191, 1.01781732],
       [0.72233637, 1.4073375 ],
       [0.48372281, 0.97303772]])

array([[ 0.75663359,  2.04803977,  0.19342559,  1.41589134],
       [ 1.10719629,  1.8740681 ,  1.89573038, -0.19585818]])

Result at step 8000 : with eR, P, Q are :


array([[1.96235166, 4.98753345, 1.02620613, 2.98585363],
       [3.81340144, 7.41371668, 5.44941662, 1.11326215],
       [1.84338996, 3.93949469, 2.09479924, 1.27022254],
       [2.07069759, 4.11210862, 2.82800925, 0.782361  ],
       [1.42191572, 2.82028154, 1.94716536, 0.53015704]])

array([[2.13849552, 0.31680231],
       [1.1484873 , 2.69095547],
       [1.02467045, 0.97679738],
       [0.73769602, 1.3824881 ],
       [0.50202504, 0.95246564]])

array([[ 0.75546157,  2.05398917,  0.19201163,  1.42505424],
       [ 1.09469051,  1.87841689,  1.94313647, -0.19450138]])

Result at step 9000 : with eR, P, Q are :


array([[1.95534965, 4.9860045 , 1.0298435 , 2.99072994],
       [3.83881656, 7.50361539, 5.67411041, 1.09452428],
       [1.82209739, 3.94929087, 2.07356832, 1.3299895 ],
       [2.0446738 , 4.10493349, 2.84915517, 0.80932265],
       [1.40555966, 2.8265982 , 1.95096464, 0.56630924]])

array([[2.13213348, 0.31667392],
       [1.13264326, 2.75257512],
       [1.05562853, 0.94498499],
       [0.74795086, 1.36514216],
       [0.52052649, 0.93398952]])

array([[ 0.75616304,  2.05948893,  0.18835664,  1.43109717],
       [ 1.08347764,  1.87858602,  1.98387666, -0.19123848]])

array([[1.95117063, 4.98517432, 1.03176965, 2.99282651],
       [3.85718752, 7.56829028, 5.86235335, 1.08108386],
       [1.80685063, 3.9576025 , 2.05684342, 1.37831558],
       [2.02452033, 4.09709787, 2.86845375, 0.83118061],
       [1.39316267, 2.83264983, 1.9517537 , 0.59999896]])

In [ ]:
nP

array([[2.12647362, 0.31724894],
       [1.1193198 , 2.80230141],
       [1.08050846, 0.92048377],
       [0.7557432 , 1.35219464],
       [0.53793855, 0.91789777]])

In [ ]:
nQ

array([[ 0.75734161,  2.06443617,  0.18406842,  1.43539407],
       [ 1.07393161,  1.87614579,  2.01845594, -0.18755339]])

In [ ]:
# https://arxiv.org/pdf/1809.00979.pdf